version: '2.2'
services:
  chatty:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chattyweb
    links:
      - redis
    ports:
      - "8080-8088:8080"
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  mysqldb:
    image: mysql:8
    hostname: mysqldb
    ports:
      - '3307:3307'
    expose:
      - '3307'

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb

